eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

server:
  port: 9004
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9002

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: user-service