eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9003
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9002
  sleuth:
    sampler:
      percentage: 1.0